def is_it_true(anything):
    return True if anything else False

a_list = ['a', 'b', 'c', 'd']
print('List: ' + str(a_list))
print('a_list[0]: ' + str(a_list[0]))
print('a_list[3]: ' + str(a_list[3]))
print('a_list[-1]: ' + str(a_list[-1]))
print('a_list[-4]: ' + str(a_list[-4]))
print()
print('List: ' + str(a_list))
print('a_list[0:2]: ' + str(a_list[0:2]))
print('a_list[1:3]: ' + str(a_list[1:3]))
print('a_list[1:-1]: ' + str(a_list[1:-1]))
print('a_list[:3]: ' + str(a_list[:3]))
print('a_list[2:]: ' + str(a_list[2:]))
print()
print('\nAdd some trash')
print('List: ' + str(a_list))
a_list = a_list + ['e', 'f']
print('a_list + ["e", "f"]: ' + str(a_list))
a_list.append('g')
print('a_list.append("g"): ' + str(a_list))
a_list.extend(['h','i'])
print('a_list.extend(["h","i"]): ' + str(a_list))
a_list.insert(0, '_')
print('a_list.insert(0, "_"): ' + str(a_list))
print('Attention:')
a_list.append(['a', 'b', 'c', 'd'])
print('List: ' + str(a_list))
print('Size of len(a_list): ' + str(len(a_list)))
print('a_list[-1]: ' + str(a_list[-1]))
a_list = a_list[1:5]
a_list.extend(['a', 'e', 'f'])
print()
print('\nSearching for p***')
print('List: ' + str(a_list))
print('a_list.count("a"): ' + str(a_list.count('a')))
print('a_list.count("c"): ' + str(a_list.count('c')))
print('"c" in a_list: ' + str('c' in a_list))
print('a_list.index("c"): ' + str(a_list.index('c')))
print('\tException ValueError if no element.')
print()
print('\nDeleting')
print('List: ' + str(a_list))
del a_list[4]
print('del a_list[4]: ' + str(a_list))
a_list.remove('f')
print('a_list.remove("f"): ' + str(a_list))
print('a_list.pop(): ' + str(a_list.pop()))
print('List: ' + str(a_list))
print('a_list.pop(1): ' + str(a_list.pop(1)))
print('List: ' + str(a_list))
print('\tException IndexError if call pop() on null list')
print()
print('\nList in logical context')
print('is_it_true([]): ' + str(is_it_true([])))
print('is_it_true(["a"]): ' + str(is_it_true(['a'])))
print('is_it_true([False]): ' + str(is_it_true([False])))
